### PR TITLE
[WIP] Add Information icon

### PR DESCRIPTION
**Pull request by leeBigCommerce**
For use with tooltips

Screen Shot 2019-12-17 at 9 12 35 am

### CODE REVIEW

**Comment by leeBigCommerce** [comment]
N.B. this may not be needed - having design review to confirm

**Comment by chanceaclark** [comment]
We will definitely need the info icon for Alerts coming soon, but it looks like you are using the outlined icon, rather than the rounded variation. Did you use the downloader script in `packages/big-design-icons`?

**Comment by deini** [comment]
@leeBigCommerce are there any plans to revive this PR? Or should we close it?

**Comment by chanceaclark** [comment]
I think I added the correct version of the icon in the messaging PR.

**Comment by deini** [comment]
Stale PR

**Pull request closed without merging**
