### PR TITLE
feat(component): copy content within the column (worksheet)

### PR DESCRIPTION
**Pull request by bc-apostoliuk**
## What?

1. Auto-filing of the full column by the value from the double-clicked "auto-fill" handler.
2. Auto-filing of the multiple cells by dragging the "auto-fill" handler.
3. Selection of the multiple cells by dragging the pointer after the mouse down.

## Why?

To extend the worksheet with the new functionality.
## Screenshots/Screen Recordings

https://user-images.githubusercontent.com/84462142/216976501-0f552c02-584f-4e0d-b89b-e8e2931efc77.mov

## Testing/Proof
Locally.

### CODE REVIEW

**Review by jorgemoya — COMMENTED** [review]
Functionality looks great but looks like we're missing tests to test this functionality. 🙏

**Comment by vdm-kr** [comment]
@eugene-polev the 1st one is the pattern from our bulk edit

**Comment by bc-apostoliuk** [comment]
@jorgemoya
 I have covered by tests the double-click auto-fill functionally which is described in the first point. Currently, we can’t test the multi-selection functionally because we have implemented only using the mouse pointer by dragging the handler. The `jsdom` environment doesn’t allow tracking the mouse, elements' position, and so on. 
I suggest finishing the covering of this part of the functionality in the next PRs where the identical behavior gonna be implemented but with using the keyboard navigations.

**Review by jorgemoya — APPROVED** [review]
Looks good to me, as long as design approves on the functionality. Regarding tests, yes lets tackle the remaining functionality in an additional PR when the keyboard functionality is added.

**Review by vdm-kr — APPROVED** [review]
lgtm

**Pull request merged**
