### PR TITLE
feat(icons): Add Home/KeyboardDoubleArrowLeftIcon/SwapHoriz icons

### PR DESCRIPTION
**Pull request by icatalina**
## What?

Add the following icons:

- Home
- KeyboardDoubleArrowLeftIcon
- SwapHoriz

## Why?

They are used by some of our apps.

## Screenshots/Screen Recordings

image

image

image

## Testing/Proof

```
big-design/big-design/icons$ npm pack
app$ npm install bigcommerce-big-design-icons-0.17.0.tgz
```

Checked that the icons look correctly.

---

Ensured that the `xmlns` attribute is excluded from components. It's not needed for inlined SVGs.

### CODE REVIEW

**Review by jorgemoya — APPROVED** [review]

**Comment by jorgemoya** [comment]
`KeyboardDoubleArrowLeftIcon` seems a little too long of a name but 🍹

**Review by chanceaclark — APPROVED** [review]
LGTM

I'll take care of merging and releasing for you @icatalina

**Comment by icatalina** [comment]
> `KeyboardDoubleArrowLeftIcon` seems a little too long of a name but 🍹 

do we change them? I kept the name in material icons

**Comment by jorgemoya** [comment]
> > `KeyboardDoubleArrowLeftIcon` seems a little too long of a name but 🍹
> 
> do we change them? I kept the name in material icons

I guess we don't. Just making the observation that the name makes more sense in the material icons library, but less so for us (why is keyboard appended anyway). I can see how it can get messy if we come up with names tho. 👍

**Comment by icatalina** [comment]
💯

**Pull request merged**
