### PR TITLE
feat(docs): add dark mode icon

### PR DESCRIPTION
**Pull request by chanceaclark**
## What?

Adds dark mode favicon to the documentation.

## Why?

QoL for your bookmarks/tabs.

## Screenshots/Screen Recordings

**Dark Mode:**
Screen Shot 2021-07-13 at 14 35 24

**Light Mode:**
Screen Shot 2021-07-13 at 14 35 40

### CODE REVIEW

**Review by tekstrand — COMMENTED** [review]
Consider running svg through optimizer. Code looks good though

https://jakearchibald.github.io/svgomg/

**Comment by chanceaclark** [comment]
@tekstrand I already ran it through [ImageOptim](https://imageoptim.com/mac) (uses SVGO) 😉

**Comment by tekstrand** [comment]
🤔 it seems to indicate more savings possible
`559 bytes → 477 bytes 85.33%`

**Comment by chanceaclark** [comment]
I'm not entirely worried about 82 bytes if I've already ran it through an optimizer  🤷

**Review by jorgemoya — APPROVED** [review]

**Review by golcinho — APPROVED** [review]

**Pull request merged**
