### PR TITLE
chore(common): APPSEC-705 Add SECURITY.md

### PR DESCRIPTION
**Pull request by bc-donfran**
## What?
Add SECURITY.md.

## Why?
Helps researchers/Github users report security bugs to us.

## Testing / Proof
NA

### CODE REVIEW

**Comment by PascalZajac** [comment]
You'll need to amend your commit message to use one of the defined scopes, plus fix the casing.

I checked some other open-source repositories like https://github.com/bigcommerce/checkout-js and https://github.com/bigcommerce/cornerstone and can't find another `SECURITY.md` to compare to, is this our new standard?

**Comment by bc-donfran** [comment]
Hey Pascal :D Fixed up the linting issue and PRs have been made for checkout-js and cornerstone. The closest you will see would be for catalyst found here: https://github.com/bigcommerce/catalyst/blob/main/SECURITY.md. This will be the standard for our commonly used repos so that we can reliably get researchers to submit any security bugs to us for BugCrowd and this came off a discussion from this issue: https://github.com/bigcommerce/bigcommerce-for-wordpress/issues/338 which was left public and open and unknown.

**Review by PascalZajac — APPROVED** [review]
Thanks for the explanation.

The text in this version seems slightly more polished than the Catalyst repository, I take it that will be updated to match?

**Comment by bc-donfran** [comment]
Yes it will be.

**Pull request merged**
