### PR TITLE
fix(component): makes label prop required for dropdown groups

### PR DESCRIPTION
**Pull request by jordan-massingill**

### CODE REVIEW

**Comment by jordan-massingill** [comment]
*quick note* - discovered that, while `options` aren't set as required prop for dropdowns (and therefore have not been made required for dropdown option groups), the dropdown will not render without them. May want to make them required as well as either part of this ticket or as part of another.

**Comment by chanceaclark** [comment]
> _quick note_ - discovered that, while `options` aren't set as required prop for dropdowns (and therefore have not been made required for dropdown option groups), the dropdown will not render without them. May want to make them required as well, either part of this ticket or as part of another.

Probably a good idea to add to this PR too.

**Comment by jorgemoya** [comment]
I believe `options` are are set as `required` in https://github.com/bigcommerce/big-design/blob/master/packages/big-design/src/components/Dropdown/types.ts#L9, unless I'm missing something.

**Comment by jorgemoya** [comment]
I think I see what you mean now. Docs are incorrect. Would be cool if you can fix them and mark as required. 🙏

**Comment by jordan-massingill** [comment]
> Probably a good idea to add to this PR too.

Done 👍

**Pull request merged**
